activation:
  entropy_wave_duration_s: 8
  field_radius_km: 2.5
  recovery_delay_s: 60
deployment:
- ground emplacement
- orbital drop node
- deep void anchor
function:
- Localized AI cognition disruption
- System logic chain degradation
- Failsafe communication nullification
integration:
  recommended_for: AI-rich theaters / black AI suppression
  stackable_with:
  - Echo Fang Array
  - EMP Singularity
name: Tower of Silence
power_source: quantum_entropy_core
signature_emission: Zero-phase static bloom
status: ultra_classified
system_id: GFC-TOS007
type: entropy_field_generator
